export const SKIP_PREFLIGHT_CHECK = process.env.SKIP_PREFLIGHT_CHECK || `true`
export const REACT_APP_DIRECTUS_URL = process.env.REACT_APP_DIRECTUS_URL || `https://localhost:8572/`
export const REACT_APP_DEV_URL = process.env.REACT_APP_DEV_URL
export const REACT_APP_DIRECTUS_TOKEN = `@spiderman03`
export const NODE_ENV = process.env.NODE_ENV || `development`
export const LOCAL_AUTH_TOKEN_KEY = process.env.LOCAL_AUTH_TOKEN_KEY || `tokenKey`
export const COMPANY_ROLE = process.env.COMPANY_ROLE || `69EB398A-E245-4DC0-9CE6-6A209EE5EDF9`
export const PORT = process.env.PORT || `8572`
export const WDS_SOCKET_PORT = process.env.WDS_SOCKET_PORT || `0`
export const SENDGRID_LINK_TO_SEND_FORGOT_PASSWORD = process.env.SENDGRID_LINK_TO_SEND_FORGOT_PASSWORD
export const SENDGRID_LINK = process.env.SENDGRID_LINK
export const SENDGRID_EMAIL_SENDER = process.env.SENDGRID_EMAIL_SENDER
export const SENDGRID_SENDER_NAME = process.env.SENDGRID_SENDER_NAME