export const REACT_APP_DIRECTUS_URL = process.env.REACT_APP_DIRECTUS_URL || `https://localhost:8572/`
export const REACT_APP_DIRECTUS_TOKEN = process.env.REACT_APP_DIRECTUS_TOKEN || `@spiderman03`
export const LOCAL_AUTH_TOKEN_KEY = process.env.REACT_APP_LOCAL_AUTH_TOKEN_KEY || `tokenKey`
export const COMPANY_ROLE = process.env.REACT_APP_COMPANY_ROLE || `69EB398A-E245-4DC0-9CE6-6A209EE5EDF9`
export const SENDGRID_LINK_TO_SEND_FORGOT_PASSWORD = process.env.REACT_APP_SENDGRID_LINK_TO_SEND_FORGOT_PASSWORD
export const SENDGRID_LINK = process.env.REACT_APP_SENDGRID_LINK
export const SENDGRID_EMAIL_SENDER = process.env.REACT_APP_SENDGRID_EMAIL_SENDER
export const SENDGRID_SENDER_NAME = process.env.REACT_APP_SENDGRID_SENDER_NAME